import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { generateMissingPlaywrightTests } from "../../../agent/src/playwright-recipe-generator";
import type { AutomationMap, CoverageGap } from "../../../agent/src/types";

const roots: string[] = [];
const map: AutomationMap = {
  version: 1,
  projectId: "sts-playwright",
  scanRoots: [{ path: "frontend/e2e", runner: "playwright", executable: true }],
  excludeDirectories: [],
  generatedRoot: "frontend/e2e/generated",
  functions: Array.from({ length: 11 }, (_, index) => ({ id: `FN-STS-${String(index + 1).padStart(2, "0")}`, name: `Function ${index + 1}`, keywords: [`fn-${index + 1}`] })) as AutomationMap["functions"],
  explicitMappings: [],
  coverageTargets: [],
  recipes: [{
    id: "login",
    output: "fn-sts-01/login.spec.ts",
    route: "/login",
    assertions: [{ kind: "url-matches", value: "\\/login" }],
  }],
};

const gap: CoverageGap = { targetId: "TC-STS-01-LOGIN", functionId: "FN-STS-01", title: "Login", status: "ready-to-generate", recipeId: "login" };

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true })));
});

describe("Playwright recipe generator", () => {
  it("writes a traceable generated spec inside generatedRoot", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-generator-"));
    roots.push(root);
    const result = await generateMissingPlaywrightTests({ workspaceRoot: root, map, gaps: [gap] });
    expect(result[0].status).toBe("generated");
    const content = await fs.readFile(path.join(root, "frontend/e2e/generated/fn-sts-01/login.spec.ts"), "utf8");
    expect(content).toContain("@generated by Morniter Local Agent");
    expect(content).toContain("TC-STS-01-LOGIN");
  });

  it("refuses to overwrite a manual file", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-generator-"));
    roots.push(root);
    const target = path.join(root, "frontend/e2e/generated/fn-sts-01/login.spec.ts");
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, "import { test } from '@playwright/test';", "utf8");
    await expect(generateMissingPlaywrightTests({ workspaceRoot: root, map, gaps: [gap] })).rejects.toThrow(/manual file/i);
  });
});

