import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import { executeRecipeMutation } from "../../../agent/src/recipe-mutator";
import type { AgentConfig, RecipeSaveMutation } from "../../../agent/src/types";

const tempRoots: string[] = [];

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((r) => fs.rm(r, { recursive: true, force: true })));
});

describe("Local Agent Recipe Mutator", () => {
  it("atomically saves a verified recipe and generates Playwright spec", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-mutator-"));
    tempRoots.push(root);

    const initialMap = {
      version: 2,
      projectId: "sts-playwright",
      runnerProfiles: [],
      scanRoots: [{ path: "frontend/e2e", runner: "playwright", executable: true }],
      excludeDirectories: [],
      generatedRoot: "frontend/e2e/generated",
      functions: [{ id: "FN-STS-01", name: "Auth", keywords: ["auth"] }],
      explicitMappings: [],
      coverageTargets: [],
      recipes: [],
    };

    const mapPath = path.join(root, "test-automation-map.json");
    const mapContent = JSON.stringify(initialMap, null, 2);
    await fs.writeFile(mapPath, mapContent, "utf8");
    const baseRevision = crypto.createHash("sha256").update(mapContent).digest("hex");

    const config: AgentConfig = {
      agentId: "test-agent",
      serverUrl: "http://localhost:3000",
      agentToken: "secret",
      projects: [
        {
          id: "sts-playwright",
          name: "ProjectSTS",
          playwright: {
            workspaceRoot: root,
            automationMap: "test-automation-map.json",
          },
        },
      ],
    };

    const mutation: RecipeSaveMutation = {
      id: "mut-01",
      agentId: "test-agent",
      projectId: "sts-playwright",
      baseRevision,
      recipe: {
        id: "recipe-login-01",
        title: "Login spec test",
        functionId: "FN-STS-01",
        output: "frontend/e2e/generated/fn-sts-01/login.spec.ts",
        risk: "read-only",
        actions: [{ kind: "goto", url: "/login" }],
      },
      status: "claimed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const result = await executeRecipeMutation(config, mutation, { skipPlaywrightList: true });
    expect(result.status).toBe("succeeded");
    expect(result.newRevision).toBeDefined();

    // Spec was written
    const specPath = path.join(root, "frontend/e2e/generated/fn-sts-01/login.spec.ts");
    const specContent = await fs.readFile(specPath, "utf8");
    expect(specContent).toContain("@generated by Morniter Recipe Builder");
    expect(specContent).toContain("@recipeId recipe-login-01");

    // Map was updated
    const updatedMapContent = await fs.readFile(mapPath, "utf8");
    const updatedMap = JSON.parse(updatedMapContent);
    expect(updatedMap.recipes).toHaveLength(1);
    expect(updatedMap.recipes[0].id).toBe("recipe-login-01");
  });

  it("detects revision conflict if map was modified concurrently", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-mutator-"));
    tempRoots.push(root);

    const mapPath = path.join(root, "test-automation-map.json");
    await fs.writeFile(mapPath, JSON.stringify({ version: 2, recipes: [] }), "utf8");

    const config: AgentConfig = {
      agentId: "test-agent",
      serverUrl: "http://localhost:3000",
      agentToken: "secret",
      projects: [
        {
          id: "sts-playwright",
          name: "ProjectSTS",
          playwright: {
            workspaceRoot: root,
            automationMap: "test-automation-map.json",
          },
        },
      ],
    };

    const mutation: RecipeSaveMutation = {
      id: "mut-02",
      agentId: "test-agent",
      projectId: "sts-playwright",
      baseRevision: "stale-revision-hash",
      recipe: {
        id: "recipe-login-01",
        title: "Login spec test",
        functionId: "FN-STS-01",
        output: "frontend/e2e/generated/fn-sts-01/login.spec.ts",
        risk: "read-only",
        actions: [{ kind: "goto", url: "/login" }],
      },
      status: "claimed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const result = await executeRecipeMutation(config, mutation, { skipPlaywrightList: true });
    expect(result.status).toBe("conflict");
  });

  it("refuses to overwrite manual non-generated test files", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-mutator-"));
    tempRoots.push(root);

    const initialMap = {
      version: 2,
      projectId: "sts-playwright",
      runnerProfiles: [],
      scanRoots: [{ path: "frontend/e2e", runner: "playwright", executable: true }],
      excludeDirectories: [],
      generatedRoot: "frontend/e2e/generated",
      functions: [{ id: "FN-STS-01", name: "Auth", keywords: ["auth"] }],
      explicitMappings: [],
      coverageTargets: [],
      recipes: [],
    };

    const mapPath = path.join(root, "test-automation-map.json");
    const mapContent = JSON.stringify(initialMap, null, 2);
    await fs.writeFile(mapPath, mapContent, "utf8");
    const baseRevision = crypto.createHash("sha256").update(mapContent).digest("hex");

    // Create existing manual file
    const manualPath = path.join(root, "frontend/e2e/generated/fn-sts-01/manual.spec.ts");
    await fs.mkdir(path.dirname(manualPath), { recursive: true });
    await fs.writeFile(manualPath, "// handwritten manual spec\ntest('manual', () => {});", "utf8");

    const config: AgentConfig = {
      agentId: "test-agent",
      serverUrl: "http://localhost:3000",
      agentToken: "secret",
      projects: [
        {
          id: "sts-playwright",
          name: "ProjectSTS",
          playwright: {
            workspaceRoot: root,
            automationMap: "test-automation-map.json",
          },
        },
      ],
    };

    const mutation: RecipeSaveMutation = {
      id: "mut-03",
      agentId: "test-agent",
      projectId: "sts-playwright",
      baseRevision,
      recipe: {
        id: "recipe-login-01",
        title: "Login spec test",
        functionId: "FN-STS-01",
        output: "frontend/e2e/generated/fn-sts-01/manual.spec.ts",
        risk: "read-only",
        actions: [{ kind: "goto", url: "/login" }],
      },
      status: "claimed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const result = await executeRecipeMutation(config, mutation, { skipPlaywrightList: true });
    expect(result.status).toBe("rejected");
    expect(result.error).toMatch(/manual|refusing to overwrite/i);
  });

  it("rejects mutating recipes targeting production denylist", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-mutator-"));
    tempRoots.push(root);

    const initialMap = {
      version: 2,
      projectId: "sts-playwright",
      productionHostDenylist: ["projectsts.com"],
      runnerProfiles: [],
      scanRoots: [{ path: "frontend/e2e", runner: "playwright", executable: true }],
      excludeDirectories: [],
      generatedRoot: "frontend/e2e/generated",
      functions: [{ id: "FN-STS-01", name: "Auth", keywords: ["auth"] }],
      explicitMappings: [],
      coverageTargets: [],
      recipes: [],
    };

    const mapPath = path.join(root, "test-automation-map.json");
    const mapContent = JSON.stringify(initialMap, null, 2);
    await fs.writeFile(mapPath, mapContent, "utf8");
    const baseRevision = crypto.createHash("sha256").update(mapContent).digest("hex");

    const config: AgentConfig = {
      agentId: "test-agent",
      serverUrl: "http://localhost:3000",
      agentToken: "secret",
      projects: [
        {
          id: "sts-playwright",
          name: "ProjectSTS",
          playwright: {
            workspaceRoot: root,
            automationMap: "test-automation-map.json",
          },
        },
      ],
    };

    const mutation: RecipeSaveMutation = {
      id: "mut-04",
      agentId: "test-agent",
      projectId: "sts-playwright",
      baseRevision,
      recipe: {
        id: "recipe-mut-prod",
        title: "Mutating on production",
        functionId: "FN-STS-01",
        output: "frontend/e2e/generated/fn-sts-01/mut-prod.spec.ts",
        risk: "mutating",
        actions: [{ kind: "goto", url: "https://app.projectsts.com/delete-all" }],
        cleanupActions: [{ kind: "goto", url: "/cleanup" }],
      },
      status: "claimed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const result = await executeRecipeMutation(config, mutation, { skipPlaywrightList: true });
    expect(result.status).toBe("rejected");
    expect(result.error).toMatch(/production denylist/i);
  });

  it("rejects mutating recipes when production URL is inside a reusable flow", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "morniter-mutator-"));
    tempRoots.push(root);

    const initialMap = {
      version: 2,
      projectId: "sts-playwright",
      productionHostDenylist: ["projectsts.com"],
      reusableFlows: [
        {
          id: "flow-prod-login",
          name: "Prod Login",
          actions: [
            { kind: "goto", url: "https://api.projectsts.com/v1/auth" },
          ],
        },
      ],
      runnerProfiles: [],
      scanRoots: [{ path: "frontend/e2e", runner: "playwright", executable: true }],
      excludeDirectories: [],
      generatedRoot: "frontend/e2e/generated",
      functions: [{ id: "FN-STS-01", name: "Auth", keywords: ["auth"] }],
      explicitMappings: [],
      coverageTargets: [],
      recipes: [],
    };

    const mapPath = path.join(root, "test-automation-map.json");
    const mapContent = JSON.stringify(initialMap, null, 2);
    await fs.writeFile(mapPath, mapContent, "utf8");
    const baseRevision = crypto.createHash("sha256").update(mapContent).digest("hex");

    const config: AgentConfig = {
      agentId: "test-agent",
      serverUrl: "http://localhost:3000",
      agentToken: "secret",
      projects: [
        {
          id: "sts-playwright",
          name: "ProjectSTS",
          playwright: {
            workspaceRoot: root,
            automationMap: "test-automation-map.json",
          },
        },
      ],
    };

    const mutation: RecipeSaveMutation = {
      id: "mut-05",
      agentId: "test-agent",
      projectId: "sts-playwright",
      baseRevision,
      recipe: {
        id: "recipe-mut-flow-prod",
        title: "Mutating with flow on production",
        functionId: "FN-STS-01",
        output: "frontend/e2e/generated/fn-sts-01/mut-flow.spec.ts",
        risk: "mutating",
        actions: [{ kind: "use-flow", flowId: "flow-prod-login" }],
        cleanupActions: [{ kind: "goto", url: "/cleanup" }],
      },
      status: "claimed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const result = await executeRecipeMutation(config, mutation, { skipPlaywrightList: true });
    expect(result.status).toBe("rejected");
    expect(result.error).toMatch(/production denylist/i);
  });
});
