import fs from "node:fs/promises";
import path from "node:path";
import { resolveInsideRoot } from "./playwright-catalog.js";
import type { AutomationMap, AutomationRecipe, CoverageGap } from "./types.js";

export interface GeneratedTestResult {
  targetId: string;
  status: "generated" | "unchanged" | "skipped" | "stale";
  relativePath?: string;
  reason?: string;
}

const GENERATED_HEADER = "// @generated by Morniter Local Agent";

function renderAssertion(assertion: AutomationRecipe["assertions"][number]): string {
  switch (assertion.kind) {
    case "role-visible":
      return `  await expect(page.getByRole(${JSON.stringify(assertion.role)}, { name: ${JSON.stringify(assertion.name)} })).toBeVisible();`;
    case "heading-visible":
      return `  await expect(page.getByRole("heading", { name: ${JSON.stringify(assertion.name)} })).toBeVisible();`;
    case "text-visible":
      return `  await expect(page.getByText(${JSON.stringify(assertion.name)})).toBeVisible();`;
    case "url-matches":
      return `  await expect(page).toHaveURL(new RegExp(${JSON.stringify(assertion.value)}));`;
  }
}

function renderSpec(target: CoverageGap, recipe: AutomationRecipe): string {
  const assertions = recipe.assertions.map(renderAssertion).join("\n");
  return [
    GENERATED_HEADER,
    `// target: ${target.targetId}`,
    `// recipe: ${recipe.id}`,
    "",
    'import { test, expect } from "@playwright/test";',
    "",
    `test(${JSON.stringify(`${target.targetId} ${target.title}`)}, async ({ page }) => {`,
    `  await page.goto(${JSON.stringify(recipe.route)});`,
    assertions,
    "});",
    "",
  ].join("\n");
}

export async function generateMissingPlaywrightTests(args: {
  workspaceRoot: string;
  map: AutomationMap;
  gaps: CoverageGap[];
}): Promise<GeneratedTestResult[]> {
  const generatedRoot = resolveInsideRoot(args.workspaceRoot, args.map.generatedRoot);
  const recipes = new Map(args.map.recipes.map((recipe) => [recipe.id, recipe]));
  const results: GeneratedTestResult[] = [];

  for (const gap of args.gaps) {
    if (gap.status !== "ready-to-generate" || !gap.recipeId) {
      results.push({ targetId: gap.targetId, status: "skipped", reason: gap.status });
      continue;
    }
    const recipe = recipes.get(gap.recipeId);
    if (!recipe) {
      results.push({ targetId: gap.targetId, status: "skipped", reason: "missing-recipe" });
      continue;
    }

    const outputPath = resolveInsideRoot(generatedRoot, recipe.output);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    const content = renderSpec(gap, recipe);
    let existing: string | undefined;
    try {
      existing = await fs.readFile(outputPath, "utf8");
    } catch {
      existing = undefined;
    }
    if (existing && !existing.startsWith(GENERATED_HEADER)) {
      throw new Error(`Refusing to overwrite manual file '${recipe.output}'`);
    }
    if (existing === content) {
      results.push({ targetId: gap.targetId, status: "unchanged", relativePath: path.relative(args.workspaceRoot, outputPath).replace(/\\/g, "/") });
      continue;
    }
    const tempPath = `${outputPath}.${process.pid}.tmp`;
    const backupPath = `${outputPath}.${process.pid}.bak`;
    await fs.writeFile(tempPath, content, "utf8");
    try {
      // Windows cannot rename a file over an existing destination. Keep a
      // generated backup while replacing it so a failed rename can restore
      // the previous generated spec.
      if (existing !== undefined) {
        await fs.rename(outputPath, backupPath);
      }
      await fs.rename(tempPath, outputPath);
      if (existing !== undefined) {
        await fs.rm(backupPath, { force: true });
      }
    } catch (error) {
      await fs.rm(tempPath, { force: true });
      const outputExists = await fs.stat(outputPath).then(() => true).catch(() => false);
      const backupExists = await fs.stat(backupPath).then(() => true).catch(() => false);
      if (!outputExists && backupExists) {
        await fs.rename(backupPath, outputPath);
      }
      throw error;
    }
    results.push({ targetId: gap.targetId, status: "generated", relativePath: path.relative(args.workspaceRoot, outputPath).replace(/\\/g, "/") });
  }
  return results;
}

export { GENERATED_HEADER, renderAssertion, renderSpec };
