export type RecipeLocator =
  | { kind: "role"; role: "button" | "link" | "textbox" | "heading" | "checkbox" | "combobox" | "option" | "radio"; name?: string; exact?: boolean }
  | { kind: "label"; text: string; exact?: boolean }
  | { kind: "text"; text: string; exact?: boolean }
  | { kind: "test-id"; id: string };

export type RecipeAction =
  | { kind: "goto"; url: string }
  | { kind: "fill"; target: RecipeLocator; value: string; isSecretEnv?: boolean }
  | { kind: "click"; target: RecipeLocator }
  | { kind: "select"; target: RecipeLocator; value: string }
  | { kind: "expect-visible"; target: RecipeLocator; timeoutMs?: number }
  | { kind: "expect-url"; url: string; matchType?: "exact" | "contains" }
  | { kind: "expect-text"; target: RecipeLocator; text: string }
  | { kind: "use-flow"; flowId: string };

export interface ReusableFlow {
  id: string;
  name: string;
  description?: string;
  actions: RecipeAction[];
}

export interface RecipeDraft {
  id: string;
  title: string;
  description?: string;
  sourceTestId?: string;
  sourceRelativePath?: string;
  functionId: string;
  output: string;
  risk: "read-only" | "mutating";
  actions: RecipeAction[];
  cleanupActions?: RecipeAction[];
}

function escapeRegex(string: string): string {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function renderLocator(loc: RecipeLocator): string {
  switch (loc.kind) {
    case "role": {
      const options: string[] = [];
      if (loc.name !== undefined) {
        options.push(`name: ${JSON.stringify(loc.name)}`);
      }
      if (loc.exact) {
        options.push("exact: true");
      }
      const optStr = options.length > 0 ? `, { ${options.join(", ")} }` : "";
      return `page.getByRole(${JSON.stringify(loc.role)}${optStr})`;
    }
    case "label": {
      const optStr = loc.exact ? ", { exact: true }" : "";
      return `page.getByLabel(${JSON.stringify(loc.text)}${optStr})`;
    }
    case "text": {
      const optStr = loc.exact ? ", { exact: true }" : "";
      return `page.getByText(${JSON.stringify(loc.text)}${optStr})`;
    }
    case "test-id": {
      return `page.getByTestId(${JSON.stringify(loc.id)})`;
    }
    default: {
      throw new Error(`Unsupported locator kind: ${(loc as { kind: string }).kind}`);
    }
  }
}

export function renderAction(
  action: RecipeAction,
  indent: string,
  flowsMap: Map<string, ReusableFlow>,
  visitedFlows: Set<string> = new Set(),
): string[] {
  switch (action.kind) {
    case "use-flow": {
      const flow = flowsMap.get(action.flowId);
      if (!flow) {
        throw new Error(`Referenced reusable flow '${action.flowId}' was not found in catalog`);
      }
      if (visitedFlows.has(action.flowId)) {
        throw new Error(`Cyclic flow reference detected in flow '${action.flowId}'`);
      }
      const nextVisited = new Set(visitedFlows);
      nextVisited.add(action.flowId);

      const lines: string[] = [`${indent}// Step Flow: ${flow.name}`];
      for (const flowAction of flow.actions) {
        lines.push(...renderAction(flowAction, indent, flowsMap, nextVisited));
      }
      return lines;
    }
    case "goto": {
      return [`${indent}await page.goto(${JSON.stringify(action.url)});`];
    }
    case "fill": {
      const loc = renderLocator(action.target);
      if (action.isSecretEnv) {
        return [`${indent}await ${loc}.fill(requireTestEnv(${JSON.stringify(action.value)}));`];
      }
      return [`${indent}await ${loc}.fill(${JSON.stringify(action.value)});`];
    }
    case "click": {
      const loc = renderLocator(action.target);
      return [`${indent}await ${loc}.click();`];
    }
    case "select": {
      const loc = renderLocator(action.target);
      return [`${indent}await ${loc}.selectOption(${JSON.stringify(action.value)});`];
    }
    case "expect-visible": {
      const loc = renderLocator(action.target);
      if (action.timeoutMs) {
        return [`${indent}await expect(${loc}).toBeVisible({ timeout: ${action.timeoutMs} });`];
      }
      return [`${indent}await expect(${loc}).toBeVisible();`];
    }
    case "expect-url": {
      if (action.matchType === "contains") {
        return [`${indent}await expect(page).toHaveURL(new RegExp(${JSON.stringify(escapeRegex(action.url))}));`];
      }
      return [`${indent}await expect(page).toHaveURL(${JSON.stringify(action.url)});`];
    }
    case "expect-text": {
      const loc = renderLocator(action.target);
      return [`${indent}await expect(${loc}).toContainText(${JSON.stringify(action.text)});`];
    }
    default: {
      throw new Error(`Unsupported action kind: ${(action as { kind: string }).kind}`);
    }
  }
}

export function renderRecipeToPlaywrightCode(
  recipe: RecipeDraft,
  flows: ReusableFlow[] = [],
): string {
  const flowsMap = new Map<string, ReusableFlow>(flows.map((f) => [f.id, f]));

  const lines: string[] = [
    "/**",
    " * @generated by Morniter Recipe Builder",
    ` * @recipeId ${recipe.id}`,
    ` * @title ${recipe.title}`,
    " * DO NOT EDIT MANUALLY - Use Morniter Recipe Builder",
    " */",
    'import { test, expect } from "@playwright/test";',
    "",
    "function requireTestEnv(name: string): string {",
    "  const value = process.env[name];",
    "  if (!value) {",
    '    throw new Error(`Missing required test environment variable: ${name}`);',
    "  }",
    "  return value;",
    "}",
    "",
    `test(${JSON.stringify(recipe.title)}, async ({ page }) => {`,
  ];

  if (recipe.risk === "mutating" && recipe.cleanupActions && recipe.cleanupActions.length > 0) {
    lines.push("  try {");
    for (const action of recipe.actions) {
      lines.push(...renderAction(action, "    ", flowsMap));
    }
    lines.push("  } finally {");
    for (const cleanupAction of recipe.cleanupActions) {
      lines.push(...renderAction(cleanupAction, "    ", flowsMap));
    }
    lines.push("  }");
  } else {
    for (const action of recipe.actions) {
      lines.push(...renderAction(action, "  ", flowsMap));
    }
  }

  lines.push("});");
  lines.push("");

  return lines.join("\n");
}
