import { describe, expect, it } from "vitest";
import { renderRecipeToPlaywrightCode } from "@/lib/playwright-runner/recipe-renderer";
import type { RecipeDraft, ReusableFlow } from "@/lib/playwright-runner/recipe-types";

describe("Recipe Deterministic Code Renderer", () => {
  const flows: ReusableFlow[] = [
    {
      id: "flow-login-uat",
      name: "Login as UAT user",
      actions: [
        { kind: "goto", url: "/login" },
        {
          kind: "fill",
          target: { kind: "label", text: "Username" },
          value: "STS_UAT_USERNAME",
          isSecretEnv: true,
        },
        {
          kind: "fill",
          target: { kind: "label", text: "Password" },
          value: "STS_UAT_PASSWORD",
          isSecretEnv: true,
        },
        {
          kind: "click",
          target: { kind: "role", role: "button", name: "Sign In" },
        },
      ],
    },
  ];

  it("renders standard recipe with generated headers and test blocks", () => {
    const recipe: RecipeDraft = {
      id: "recipe-login-check",
      title: "Verify login and home navigation",
      functionId: "FN-STS-01",
      output: "frontend/e2e/generated/fn-sts-01/login.spec.ts",
      risk: "read-only",
      actions: [
        { kind: "use-flow", flowId: "flow-login-uat" },
        { kind: "expect-url", url: "/dashboard", matchType: "contains" },
        {
          kind: "expect-visible",
          target: { kind: "text", text: "Welcome" },
          timeoutMs: 5000,
        },
      ],
    };

    const code = renderRecipeToPlaywrightCode(recipe, flows);

    expect(code).toContain("@generated by Morniter Recipe Builder");
    expect(code).toContain("@recipeId recipe-login-check");
    expect(code).toContain('import { test, expect } from "@playwright/test";');
    expect(code).toContain('function requireTestEnv(name: string): string');
    expect(code).toContain('await page.goto("/login");');
    expect(code).toContain('page.getByLabel("Username").fill(requireTestEnv("STS_UAT_USERNAME"))');
    expect(code).toContain('page.getByRole("button", { name: "Sign In" }).click()');
    expect(code).toContain('await expect(page).toHaveURL(new RegExp("/dashboard"));');
    expect(code).toContain('await expect(page.getByText("Welcome")).toBeVisible({ timeout: 5000 });');
  });

  it("renders mutating test with cleanup in try/finally", () => {
    const recipe: RecipeDraft = {
      id: "recipe-mutating-01",
      title: "Create temporary item",
      functionId: "FN-STS-03",
      output: "frontend/e2e/generated/fn-sts-03/create.spec.ts",
      risk: "mutating",
      actions: [
        { kind: "goto", url: "/items/new" },
        { kind: "click", target: { kind: "role", role: "button", name: "Create" } },
      ],
      cleanupActions: [
        { kind: "goto", url: "/items/cleanup" },
        { kind: "click", target: { kind: "role", role: "button", name: "Delete All Temp" } },
      ],
    };

    const code = renderRecipeToPlaywrightCode(recipe);

    expect(code).toContain("try {");
    expect(code).toContain("} finally {");
    expect(code).toContain('await page.goto("/items/cleanup");');
    expect(code).toContain('page.getByRole("button", { name: "Delete All Temp" }).click()');
  });

  it("throws error when referenced flow is not found", () => {
    const recipe: RecipeDraft = {
      id: "recipe-missing-flow",
      title: "Missing flow test",
      functionId: "FN-STS-01",
      output: "frontend/e2e/generated/fn-sts-01/test.spec.ts",
      risk: "read-only",
      actions: [{ kind: "use-flow", flowId: "non-existent-flow" }],
    };

    expect(() => renderRecipeToPlaywrightCode(recipe, flows)).toThrow(/not found in catalog/i);
  });

  it("detects and rejects cyclic flow references", () => {
    const cyclicFlows: ReusableFlow[] = [
      {
        id: "flow-a",
        name: "Flow A",
        actions: [{ kind: "use-flow", flowId: "flow-b" }],
      },
      {
        id: "flow-b",
        name: "Flow B",
        actions: [{ kind: "use-flow", flowId: "flow-a" }],
      },
    ];

    const recipe: RecipeDraft = {
      id: "recipe-cycle",
      title: "Cycle test",
      functionId: "FN-STS-01",
      output: "frontend/e2e/generated/fn-sts-01/cycle.spec.ts",
      risk: "read-only",
      actions: [{ kind: "use-flow", flowId: "flow-a" }],
    };

    expect(() => renderRecipeToPlaywrightCode(recipe, cyclicFlows)).toThrow(/cyclic flow reference/i);
  });
});
